"use client";

import { useState, useRef } from "react";
import ReactMarkdown from "react-markdown";
import {
  Download,
  FileText,
  Code2,
  Wand2,
  Minimize2,
  Maximize2,
  BookOpen,
  AlignLeft,
  Copy,
  Check,
  Loader2,
} from "lucide-react";
import type { DocConfig } from "@/app/page";

const AI_ACTIONS = [
  { key: "simplify", label: "Simplify", icon: Minimize2, desc: "Simpler language" },
  { key: "expand", label: "Expand", icon: Maximize2, desc: "Add more detail" },
  { key: "example", label: "Add Example", icon: BookOpen, desc: "Add practical example" },
  { key: "troubleshoot", label: "Troubleshoot", icon: AlignLeft, desc: "Add troubleshooting" },
  { key: "concise", label: "Make Concise", icon: Code2, desc: "Remove fluff" },
];

export default function DocumentEditor({
  content,
  onChange,
  onRefine,
  config,
}: {
  content: string;
  onChange: (c: string) => void;
  onRefine: (text: string, action: string) => Promise<string>;
  config: DocConfig;
}) {
  const [view, setView] = useState<"split" | "edit" | "preview">("split");
  const [refining, setRefining] = useState(false);
  const [copied, setCopied] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const getSelectedText = (): { text: string; start: number; end: number } | null => {
    const el = textareaRef.current;
    if (!el) return null;
    const start = el.selectionStart;
    const end = el.selectionEnd;
    if (start === end) return null;
    return { text: content.slice(start, end), start, end };
  };

  const handleAIAction = async (actionKey: string) => {
    const selection = getSelectedText();
    const textToRefine = selection?.text || content;

    setRefining(true);
    try {
      const refined = await onRefine(textToRefine, actionKey);
      if (selection) {
        const newContent =
          content.slice(0, selection.start) + refined + content.slice(selection.end);
        onChange(newContent);
      } else {
        onChange(refined);
      }
    } catch {
      // Error handled silently; content unchanged
    } finally {
      setRefining(false);
    }
  };

  const exportHTML = () => {
    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Documentation</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    color: #1a1a2e; line-height: 1.7; max-width: 800px;
    margin: 0 auto; padding: 3rem 2rem; background: #ffffff;
  }
  h1 { font-size: 2rem; font-weight: 700; margin: 2rem 0 1rem; color: #0f1729; }
  h2 { font-size: 1.5rem; font-weight: 600; margin: 1.75rem 0 0.75rem; color: #0f1729;
       padding-bottom: 0.5rem; border-bottom: 2px solid #e8ecf4; }
  h3 { font-size: 1.15rem; font-weight: 600; margin: 1.5rem 0 0.5rem; color: #2b3a5c; }
  p { margin-bottom: 1rem; }
  ul, ol { margin-bottom: 1rem; padding-left: 1.5rem; }
  li { margin-bottom: 0.375rem; }
  code { background: #f1f3f9; padding: 0.15rem 0.4rem; border-radius: 4px; font-size: 0.85em; }
  pre { background: #0f1729; color: #dbe4ff; padding: 1rem 1.25rem; border-radius: 8px;
        margin-bottom: 1rem; overflow-x: auto; }
  pre code { background: none; color: inherit; padding: 0; }
  blockquote { border-left: 3px solid #4c6ef5; padding: 0.5rem 1rem; margin: 1rem 0;
               background: #f0f4ff; border-radius: 0 6px 6px 0; }
  strong { font-weight: 600; color: #0f1729; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 1rem; }
  th, td { border: 1px solid #e8ecf4; padding: 0.5rem 0.75rem; text-align: left; }
  th { background: #f8f9fc; font-weight: 600; }
  .footer { margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid #e8ecf4;
            font-size: 0.8rem; color: #8494b2; }
</style>
</head>
<body>
${markdownToBasicHTML(content)}
<div class="footer">Generated by DocCraft AI • ${new Date().toLocaleDateString()}</div>
</body>
</html>`;

    downloadFile(htmlContent, "documentation.html", "text/html");
  };

  const exportMarkdown = () => {
    downloadFile(content, "documentation.md", "text/markdown");
  };

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyToClipboard = async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="animate-fade-in-up">
      {/* Toolbar */}
      <div className="bg-white rounded-t-2xl border border-surface-3 border-b-0 px-4 py-3 flex items-center justify-between flex-wrap gap-3">
        <div className="flex items-center gap-4">
          {/* View toggle */}
          <div className="flex bg-surface-1 rounded-lg p-0.5 border border-surface-2">
            {(["edit", "split", "preview"] as const).map((v) => (
              <button
                key={v}
                onClick={() => setView(v)}
                className={`px-3 py-1 text-xs font-medium rounded-md transition-all capitalize ${
                  view === v
                    ? "bg-white text-ink-0 shadow-sm"
                    : "text-ink-3 hover:text-ink-1"
                }`}
              >
                {v}
              </button>
            ))}
          </div>

          {/* AI Actions */}
          <div className="flex items-center gap-1">
            <Wand2 size={13} className="text-brand-500 mr-1" />
            {AI_ACTIONS.map((action) => {
              const Icon = action.icon;
              return (
                <button
                  key={action.key}
                  onClick={() => handleAIAction(action.key)}
                  disabled={refining}
                  title={`${action.desc}${getSelectedText() ? " (selected text)" : " (full doc)"}`}
                  className="px-2.5 py-1 text-[0.7rem] font-medium text-ink-2 hover:text-brand-700
                             hover:bg-brand-50 rounded-md transition-colors disabled:opacity-40 flex items-center gap-1"
                >
                  <Icon size={12} />
                  {action.label}
                </button>
              );
            })}
            {refining && (
              <span className="flex items-center gap-1 text-xs text-brand-600 ml-2">
                <Loader2 size={13} className="animate-spin" />
                Refining…
              </span>
            )}
          </div>
        </div>

        {/* Export buttons */}
        <div className="flex items-center gap-1.5">
          <button
            onClick={copyToClipboard}
            className="flex items-center gap-1 px-3 py-1.5 text-xs font-medium text-ink-2
                       hover:bg-surface-2 rounded-lg transition-colors"
          >
            {copied ? <Check size={13} className="text-accent-green" /> : <Copy size={13} />}
            {copied ? "Copied" : "Copy"}
          </button>
          <button
            onClick={exportMarkdown}
            className="flex items-center gap-1 px-3 py-1.5 text-xs font-medium text-ink-2
                       hover:bg-surface-2 rounded-lg transition-colors"
          >
            <Code2 size={13} />
            .md
          </button>
          <button
            onClick={exportHTML}
            className="flex items-center gap-1 px-3 py-1.5 bg-brand-700 text-white text-xs
                       font-semibold rounded-lg hover:bg-brand-800 transition-colors shadow-sm"
          >
            <Download size={13} />
            Export HTML
          </button>
        </div>
      </div>

      {/* Editor + Preview */}
      <div className="bg-white rounded-b-2xl border border-surface-3 overflow-hidden shadow-card">
        <div
          className={`grid ${
            view === "split" ? "grid-cols-2" : "grid-cols-1"
          } divide-x divide-surface-2`}
          style={{ minHeight: "65vh" }}
        >
          {/* Editor */}
          {view !== "preview" && (
            <div className="relative">
              <div className="absolute top-3 left-4 text-[0.65rem] font-semibold text-ink-4 uppercase tracking-wider">
                Markdown
              </div>
              <textarea
                ref={textareaRef}
                value={content}
                onChange={(e) => onChange(e.target.value)}
                className="w-full h-full px-4 py-10 text-sm text-ink-1 font-mono leading-relaxed
                           focus:outline-none resize-none bg-transparent"
                spellCheck={false}
              />
            </div>
          )}

          {/* Preview */}
          {view !== "edit" && (
            <div className="relative overflow-auto">
              <div className="absolute top-3 left-4 text-[0.65rem] font-semibold text-ink-4 uppercase tracking-wider">
                Preview
              </div>
              <div className="px-8 py-10 markdown-preview">
                <ReactMarkdown>{content}</ReactMarkdown>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Tip */}
      <p className="text-center text-xs text-ink-3 mt-3">
        💡 Select text in the editor, then click an AI action to refine just that section
      </p>
    </div>
  );
}

/** Minimal markdown → HTML conversion for export (not for live preview) */
function markdownToBasicHTML(md: string): string {
  return md
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`(.+?)`/g, "<code>$1</code>")
    .replace(/^> (.+)$/gm, "<blockquote><p>$1</p></blockquote>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/^(\d+)\. (.+)$/gm, "<li>$2</li>")
    .replace(/(<li>.*<\/li>\n?)+/g, (match) =>
      match.startsWith("<li>") ? `<ul>${match}</ul>` : match
    )
    .replace(/\n\n/g, "</p><p>")
    .replace(/^(?!<[hublop])(.+)$/gm, "<p>$1</p>")
    .replace(/<p><\/p>/g, "");
}
