"use client";

import { useState } from "react";
import { Github, Globe, BookOpen, Loader2, CheckCircle2, ExternalLink, X } from "lucide-react";
import { safeResJson } from "@/lib/safeResJson";

type Tab = "github" | "confluence" | "notion";

interface PublishResult {
  url: string;
  target: string;
  action?: string;
}

export default function PublishPanel({
  content,
  docTitle,
  onClose,
}: {
  content: string;
  docTitle: string;
  onClose: () => void;
}) {
  const [tab, setTab] = useState<Tab>("github");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState<PublishResult | null>(null);

  // GitHub state
  const [ghToken, setGhToken] = useState("");
  const [ghRepoUrl, setGhRepoUrl] = useState("");
  const [ghFilePath, setGhFilePath] = useState("docs/documentation.md");
  const [ghAction, setGhAction] = useState<"pr" | "commit">("pr");
  const [ghPrTitle, setGhPrTitle] = useState(`DocCraft AI: ${docTitle}`);
  const [ghCommitMsg, setGhCommitMsg] = useState("docs: update documentation via DocCraft AI");

  // Confluence state
  const [cfBaseUrl, setCfBaseUrl] = useState("");
  const [cfEmail, setCfEmail] = useState("");
  const [cfToken, setCfToken] = useState("");
  const [cfSpaceKey, setCfSpaceKey] = useState("");
  const [cfTitle, setCfTitle] = useState(docTitle);
  const [cfParentId, setCfParentId] = useState("");

  // Notion state
  const [ntToken, setNtToken] = useState("");
  const [ntParentId, setNtParentId] = useState("");
  const [ntTitle, setNtTitle] = useState(docTitle);

  const publish = async () => {
    setLoading(true);
    setError("");
    setResult(null);

    try {
      if (tab === "github") {
        if (!ghToken || !ghRepoUrl) throw new Error("GitHub token and repository URL are required");
        const res = await fetch("/api/github-publish", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            action: ghAction,
            repoUrl: ghRepoUrl,
            filePath: ghFilePath,
            content,
            commitMessage: ghCommitMsg,
            prTitle: ghPrTitle,
            prBody: `Documentation generated by [DocCraft AI](https://doccraft-ten.vercel.app/) and published via the Publish panel.\n\nPlease review the generated content before merging.`,
            token: ghToken,
          }),
        });
        const data = await safeResJson(res);
        if (!res.ok) throw new Error(data.error || "GitHub publish failed");
        setResult({ url: data.url, target: "github", action: data.action });
      }

      if (tab === "confluence") {
        if (!cfBaseUrl || !cfEmail || !cfToken || !cfSpaceKey || !cfTitle) {
          throw new Error("All Confluence fields are required");
        }
        const res = await fetch("/api/publish", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            target: "confluence",
            baseUrl: cfBaseUrl,
            email: cfEmail,
            token: cfToken,
            spaceKey: cfSpaceKey,
            title: cfTitle,
            content,
            parentPageId: cfParentId || undefined,
          }),
        });
        const data = await safeResJson(res);
        if (!res.ok) throw new Error(data.error || "Confluence publish failed");
        setResult({ url: data.url, target: "confluence" });
      }

      if (tab === "notion") {
        if (!ntToken || !ntParentId || !ntTitle) {
          throw new Error("All Notion fields are required");
        }
        const res = await fetch("/api/publish", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            target: "notion",
            token: ntToken,
            parentPageId: ntParentId,
            title: ntTitle,
            content,
          }),
        });
        const data = await safeResJson(res);
        if (!res.ok) throw new Error(data.error || "Notion publish failed");
        setResult({ url: data.url, target: "notion" });
      }
    } catch (err: any) {
      setError(err.message || "Publish failed");
    } finally {
      setLoading(false);
    }
  };

  const TABS: { key: Tab; label: string; Icon: React.ElementType }[] = [
    { key: "github", label: "GitHub PR", Icon: Github },
    { key: "confluence", label: "Confluence", Icon: Globe },
    { key: "notion", label: "Notion", Icon: BookOpen },
  ];

  return (
    <div className="border border-surface-3 rounded-2xl bg-white shadow-card overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-5 py-3 border-b border-surface-2 bg-surface-1">
        <div className="flex items-center gap-2">
          <Globe size={15} className="text-brand-600" />
          <span className="text-sm font-semibold text-ink-0">Publish</span>
          <span className="text-[0.65rem] text-ink-4 font-medium uppercase tracking-wide bg-surface-2 px-2 py-0.5 rounded-full">
            Phase 3
          </span>
        </div>
        <button onClick={onClose} className="text-ink-4 hover:text-ink-1 transition-colors">
          <X size={15} />
        </button>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-surface-2">
        {TABS.map(({ key, label, Icon }) => (
          <button
            key={key}
            onClick={() => { setTab(key); setResult(null); setError(""); }}
            className={`flex items-center gap-1.5 px-4 py-2.5 text-xs font-medium transition-colors border-b-2 -mb-px ${
              tab === key
                ? "border-brand-600 text-brand-700"
                : "border-transparent text-ink-3 hover:text-ink-1"
            }`}
          >
            <Icon size={13} />
            {label}
          </button>
        ))}
      </div>

      <div className="p-5 space-y-3">
        {/* Success */}
        {result && (
          <div className="flex items-start gap-3 p-3 bg-green-50 border border-green-200 rounded-xl">
            <CheckCircle2 size={16} className="text-accent-green mt-0.5 shrink-0" />
            <div>
              <p className="text-xs font-semibold text-green-800">
                {result.action === "pr_created" ? "Pull request created" :
                 result.action === "committed" ? "File committed" :
                 "Published successfully"}
              </p>
              <a
                href={result.url}
                target="_blank"
                rel="noopener"
                className="inline-flex items-center gap-1 text-xs text-brand-600 hover:underline mt-0.5"
              >
                View on {result.target} <ExternalLink size={10} />
              </a>
            </div>
          </div>
        )}

        {/* GitHub tab */}
        {tab === "github" && (
          <>
            <Field label="GitHub personal access token *" hint="Needs repo scope">
              <input type="password" value={ghToken} onChange={e => setGhToken(e.target.value)} placeholder="ghp_..." className={inputCls} />
            </Field>
            <Field label="Repository URL *">
              <input type="url" value={ghRepoUrl} onChange={e => setGhRepoUrl(e.target.value)} placeholder="https://github.com/owner/repo" className={inputCls} />
            </Field>
            <Field label="File path in repo">
              <input type="text" value={ghFilePath} onChange={e => setGhFilePath(e.target.value)} placeholder="docs/documentation.md" className={inputCls} />
            </Field>
            <Field label="Action">
              <div className="flex gap-2">
                {(["pr", "commit"] as const).map(a => (
                  <button key={a} onClick={() => setGhAction(a)}
                    className={`flex-1 py-2 text-xs font-medium rounded-lg border transition-colors ${
                      ghAction === a ? "bg-brand-50 border-brand-400 text-brand-700" : "border-surface-3 text-ink-2 hover:bg-surface-2"
                    }`}>
                    {a === "pr" ? "Open Pull Request" : "Commit directly"}
                  </button>
                ))}
              </div>
            </Field>
            {ghAction === "pr" ? (
              <Field label="PR title">
                <input type="text" value={ghPrTitle} onChange={e => setGhPrTitle(e.target.value)} className={inputCls} />
              </Field>
            ) : (
              <Field label="Commit message">
                <input type="text" value={ghCommitMsg} onChange={e => setGhCommitMsg(e.target.value)} className={inputCls} />
              </Field>
            )}
          </>
        )}

        {/* Confluence tab */}
        {tab === "confluence" && (
          <>
            <Field label="Confluence base URL *" hint="e.g. https://yoursite.atlassian.net/wiki">
              <input type="url" value={cfBaseUrl} onChange={e => setCfBaseUrl(e.target.value)} placeholder="https://yoursite.atlassian.net/wiki" className={inputCls} />
            </Field>
            <Field label="Atlassian email *">
              <input type="email" value={cfEmail} onChange={e => setCfEmail(e.target.value)} placeholder="you@example.com" className={inputCls} />
            </Field>
            <Field label="Atlassian API token *">
              <input type="password" value={cfToken} onChange={e => setCfToken(e.target.value)} placeholder="Atlassian API token" className={inputCls} />
            </Field>
            <Field label="Space key *" hint="e.g. DOCS or ENG">
              <input type="text" value={cfSpaceKey} onChange={e => setCfSpaceKey(e.target.value)} placeholder="DOCS" className={inputCls} />
            </Field>
            <Field label="Page title *">
              <input type="text" value={cfTitle} onChange={e => setCfTitle(e.target.value)} className={inputCls} />
            </Field>
            <Field label="Parent page ID" hint="Optional — leave blank for root of space">
              <input type="text" value={cfParentId} onChange={e => setCfParentId(e.target.value)} placeholder="Optional" className={inputCls} />
            </Field>
          </>
        )}

        {/* Notion tab */}
        {tab === "notion" && (
          <>
            <Field label="Notion integration token *" hint="From notion.so/my-integrations">
              <input type="password" value={ntToken} onChange={e => setNtToken(e.target.value)} placeholder="secret_..." className={inputCls} />
            </Field>
            <Field label="Parent page ID *" hint="Share the page with your integration first">
              <input type="text" value={ntParentId} onChange={e => setNtParentId(e.target.value)} placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" className={inputCls} />
            </Field>
            <Field label="Page title *">
              <input type="text" value={ntTitle} onChange={e => setNtTitle(e.target.value)} className={inputCls} />
            </Field>
          </>
        )}

        {error && (
          <p className="text-xs text-accent-red bg-red-50 border border-red-200 rounded-lg px-3 py-2">
            {error}
          </p>
        )}

        <button
          onClick={publish}
          disabled={loading}
          className="w-full flex items-center justify-center gap-2 py-2.5 bg-brand-700 text-white text-sm font-semibold rounded-xl hover:bg-brand-800 transition-colors disabled:opacity-50"
        >
          {loading && <Loader2 size={14} className="animate-spin" />}
          {tab === "github"
            ? ghAction === "pr" ? "Create Pull Request" : "Commit to Repo"
            : tab === "confluence" ? "Publish to Confluence"
            : "Publish to Notion"}
        </button>
      </div>
    </div>
  );
}

const inputCls = "w-full px-3 py-2 text-sm border border-surface-3 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-200 focus:border-brand-400 bg-white";

function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) {
  return (
    <div>
      <label className="block text-xs font-medium text-ink-2 mb-1">
        {label}
        {hint && <span className="font-normal text-ink-4 ml-1">— {hint}</span>}
      </label>
      {children}
    </div>
  );
}
